name: Deploy to Server

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Run deployment script on server
        run: sshpass -p dieto123qwe!@# ssh root@66.248.207.178 'echo hello'
